import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Buyland from './buyLand'
import Drawer from '@/components/drawer/Drawer'
import 'swiper/swiper-bundle.css';
import SliderFour from '@/components/slider/SliderFour'

export default function Home() {
  return (
    <>
      <Head>
        <title>BuyLand</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
  rel="stylesheet"
  type="text/css"
  charset="UTF-8"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>  </Head>
      <main>
        {/* <Buyland /> */}
        <Drawer />
        <SliderFour />
      </main>
    </>
  )
}
