import SecondImage from "../../../assets/1.1.webp";
import ImageHouse from "../../../assets/image.jpeg";
import SecondCard from "../../../assets/secondCard.jpg";
import ThirdCard from "../../../assets/thirdCard.jpg";
import FourthCard from "../../../assets/fourthCard.jpg";
import FifthCard from "../../../assets/fifthCard.jpg";
import SixthCard from "../../../assets/sixthCard.jpg";
import SeventhCard from "../../../assets/seventhCard.jpg";

import OneHill from "../../../assets/propertyOne.webp";
import TwoHill from "../../../assets/2.1.webp";
import ThirdHill from "../../../assets/propertyThree.webp";


export const data = [
    { title: "Pure Michigan Hideaway Lodge", image: ImageHouse, route: "/property", name: "Michigan", beds: "12", bath: "8", price: "1100000", sqft: "5,700", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,
    { title: "Crystal Lake Haven", image: SecondCard, route: "/property", name: "Michigan", beds: "8", bath: "4", price: "5240000", sqft: "5152", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,

    { title: "Four Seasons Lodge", route: "/property", image: ThirdCard, name: "Michigan", beds: "8", bath: "6", price: "1250000", sqft: "4,326", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,

    { title: "Cocoa Beach House", route: "/property", image: FourthCard, name: "Michigan", beds: "4", bath: "4.5", price: "1250000", sqft: "4,084", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,

    { title: "Summer in the Hamptons", route: "/property", image: FifthCard, name: "Michigan", beds: "4", bath: "3", price: "1,199,000", sqft: "3,300", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,

    { title: "Bangrak Hills Villa", route: "/property", image: SixthCard, name: "Michigan", beds: "1", bath: "2", price: "1250000", sqft: "6000", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,
    { title: "Burj Khalifa View | Serviced Apartment | Rented", route: "/property", image: SeventhCard, name: "Michigan", beds: "12", bath: "8", price: "789,539", sqft: "840", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }

]

export const dataTwo = [
    { title: "BellAzur (5 Bedroom)", route: "/Hills", image: OneHill, name: "Michigan", beds: "12", bath: "8", price: "1250000", sqft: "6000", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }

    ,
    { title: "AsanjA Titaly", route: "/hillSecond", image: TwoHill, name: "Michigan", beds: "12", bath: "8", price: "1250000", sqft: "6000", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }
    ,
    { title: "Glasshouse Celeste", route: "/hillThird", image: ThirdHill, name: "Michigan", beds: "12", bath: "8", price: "1250000", sqft: "6000", location: "Lake Huron", overview: "Welcome to a truly exceptional property nestled along the pristine shores of Lake Huron in Michigan. This exquisite retreat offers an incredible 600 feet of private, sandy beachfront, providing a breathtaking oasis of relaxation & tranquility. Individual dimension If you are searching for the perfect blend of privacy & natural beauty, look no further. The centerpiece of this remarkable estate has the collection of three cedar log cabin-style structures, each meticulously designed & fully finished to offer detached living spaces that epitomize comfort & charm. Each unit features 2 bedrooms, 4 beds, a full bathroom, & rustic elegance with knotty pine walls. Cozy up by the fireplace or enjoy a meal in the complete kitchen. Vinyl floors, commercial-grade carpeting, and forced AC units provide comfort. Wake up to charming interiors bathed in natural light, leading to a covered porch with stunning lake views. This heavenly location also features additional structures that enhance the convenience & functionality of the property. A 2-bedroom 1 bathroom ranch house with an added check-in office sits alongside yet another two-unit ranch efficiency structure that offers even more versatility, with each unit featuring a bedroom, kitchenette, living room, and full bath. The south side of the property also consists of a 4500 sq ft pole barn with heated workshop and office, a large storage area, as well as additional ample storage rms. The 10.02-acre property offers seclusion & a haven of privacy. Immerse yourself in natural beauty, breathtaking views, & luxury" }

]